[package]
name = "testy_io"
version = "0.1.0"
authors = ["atsushi130 <atsushi_main@outlook.co.jp>"]

[dependencies]
rocket = "0.2.8"
serde  = "0.9"
serde_derive   = "0.9"
serde_json     = "0.9"
rocket_codegen = "0.2.8"
rocket_contrib = "0.2.6"